<?php

$_SERVER[ 'CLAM_TCP_ADDRESS' ] = 'tcp://172.17.0.2:3310';
$_SERVER[ 'TMP_UNZIP_DIR' ] = '/tmp';
$_SERVER[ 'SCHEMA_VERSION_SEPARATOR' ] = '|';
$_SERVER[ 'SCORM_SCHEMA_VERSION' ] = 'CAM 1.3';
$_SERVER[ 'SCORM_SCHEMA_VERSION_CASE_SENSITIVE' ] = false;
$_SERVER[ 'CAPTIVATE_SCHEMA_VERSION' ] = 'CAM 1.3|';
$_SERVER[ 'CAPTIVATE_SCHEMA_VERSION_CASE_SENSITIVE' ] = false;
$_SERVER[ 'GOOGLE_CLOUD_STORAGE_PROJECT_ID'] = '';
$_ENV[ 'GOOGLE_APPLICATION_CREDENTIALS' ] = '/home/antonis/Projects/learnworlds/ScormUpload/ScormUpload-ce5fab8b17db.json';